# Generated by Django 5.0.1 on 2024-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('autopilot', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('planemode', models.CharField(max_length=50)),
                ('armed', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('stabilized', models.BooleanField(default=False)),
                ('guided', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('test', models.BooleanField(default=False)),
            ],
        ),
    ]
