# Generated by Django 5.0.1 on 2024-01-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protosim_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat_message',
            old_name='type',
            new_name='typeMessage',
        ),
    ]
