# Generated by Django 5.0.1 on 2024-01-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protosim_django', '0002_rename_type_heartbeat_message_typemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat_message',
            old_name='typeMessage',
            new_name='m_type',
        ),
    ]
