# Generated by Django 5.0.1 on 2024-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosim_django', '0003_rename_typemessage_heartbeat_message_m_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('hexdata', models.CharField(max_length=500)),
            ],
        ),
    ]
