# Generated by Django 5.0.1 on 2024-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosim_django', '0005_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
