# Generated by Django 5.0.1 on 2024-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protosim_django', '0006_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageData',
            field=models.CharField(default=' ', max_length=1500),
            preserve_default=False,
        ),
    ]
